# Aplicacion
spring.application.name=marketplace-api
server.port=8080

# PostgreSQL para Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/marketplace_db
spring.datasource.username=marketplace_user
spring.datasource.password=marketplace_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=marketplace

# MongoDB para Docker (SIN autenticacion)
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=marketplace_logs

# Logging
logging.level.com.ConectaClick.marketplace=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=DEBUG

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Spring Boot configuration
spring.main.allow-circular-references=false
spring.jackson.time-zone=America/Bogota